# Generated by Django 5.0.4 on 2024-04-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subjectname',
            new_name='subject',
        ),
    ]
