# Generated by Django 5.0.4 on 2024-04-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_rename_subjectname_subjects_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
