# Generated by Django 5.0.4 on 2024-04-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('Std_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('Standard', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathersname', models.CharField(max_length=40)),
                ('mothersname', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('Std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app8.students')),
            ],
        ),
    ]
