# Generated by Django 5.0.4 on 2024-04-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsdetails',
            name='Std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='app8.students'),
        ),
    ]
