# Generated by Django 5.0.4 on 2024-04-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0002_alter_parentsdetails_std_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feesstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_term_fee', models.IntegerField(null=True)),
                ('second_term_fee', models.IntegerField(null=True)),
                ('third_term_fee', models.IntegerField(null=True)),
                ('bus_fee', models.IntegerField(null=True)),
                ('extra_c_fee', models.IntegerField(null=True)),
                ('pending', models.IntegerField(null=True)),
                ('Std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app8.students')),
            ],
        ),
    ]
