# Generated by Django 5.0.4 on 2024-04-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0003_feesstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstatus',
            name='bus_fee',
            field=models.IntegerField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='feesstatus',
            name='extra_c_fee',
            field=models.IntegerField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='feesstatus',
            name='first_term_fee',
            field=models.IntegerField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='feesstatus',
            name='pending',
            field=models.IntegerField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='feesstatus',
            name='second_term_fee',
            field=models.IntegerField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='feesstatus',
            name='third_term_fee',
            field=models.IntegerField(default='-', null=True),
        ),
    ]
