# Generated by Django 5.0.4 on 2024-05-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0004_alter_feesstatus_bus_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('DOB', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=40)),
                ('fathers_name', models.CharField(max_length=40)),
                ('mothers_name', models.CharField(max_length=40)),
            ],
        ),
    ]
