# Generated by Django 5.0.4 on 2024-04-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('st_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classnum', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.class')),
            ],
        ),
    ]
