# Generated by Django 5.0.4 on 2024-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stddetails',
            name='attendance',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
