# Generated by Django 5.0.4 on 2024-04-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='action',
        ),
    ]
