# Generated by Django 5.0.4 on 2024-04-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_members_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
