# Generated by Django 5.0.4 on 2024-04-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_members_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='address',
        ),
        migrations.RemoveField(
            model_name='members',
            name='subject',
        ),
    ]
