# Generated by Django 5.0.4 on 2024-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_members_address_remove_members_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
