# Generated by Django 5.0.4 on 2024-04-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_members_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
    ]
