# Generated by Django 5.0.4 on 2024-04-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_attendance_date_alter_attendance_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
