# Generated by Django 5.0.4 on 2024-04-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_attendance_date_remove_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
