# Generated by Django 5.0.4 on 2024-04-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_attendance_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classes',
            field=models.IntegerField(default=''),
        ),
    ]
