# Generated by Django 5.0.4 on 2024-04-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_attendance_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='classes',
            new_name='class_number',
        ),
    ]
