# Generated by Django 5.0.4 on 2024-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_classes_attendance_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_number',
            field=models.IntegerField(default=0),
        ),
    ]
