# Generated by Django 5.0.4 on 2024-04-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_attendance_classes_attendance_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_name',
        ),
    ]
