# Generated by Django 5.0.4 on 2024-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='standard',
            field=models.IntegerField(default=0),
        ),
    ]
