# Generated by Django 5.0.4 on 2024-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
