# Generated by Django 5.0.4 on 2024-04-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
