# Generated by Django 5.0.4 on 2024-04-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_attendancedetails_delete_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceDetails',
        ),
    ]
