# Generated by Django 5.0.4 on 2024-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_delete_attendancedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='class1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class10',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class4',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class5',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class6',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class7',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class8',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='class9',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
